"""Off-policy agents for a batched :mod:`qlsgym` belief environment.

The FNO is a fixed transition surrogate, so replay stores both quantum
measurement branches when a transition is collected.  This avoids running the
neural operator again for every replay update and retains the S18 expectation

    y(s,a) = sum_k p_k [r_k + gamma (1-d_k) V(s'_k)].

The module intentionally depends only on the small environment protocol used
below.  The agents use qlsgym's batched environment directly.
"""

from __future__ import annotations

import copy
import math
import time
from dataclasses import asdict, dataclass, field

import numpy as np
import torch
import torch.nn as nn


def transform_belief(belief: torch.Tensor) -> torch.Tensor:
    """Variance-stabilising input used by qlsgym's reference PPO."""
    return belief.to(torch.float32).clamp_min(0.0).sqrt()


def build_mlp(n_in: int, n_out: int, hidden: int, depth: int,
              output_gain: float = 1.0) -> nn.Sequential:
    layers: list[nn.Module] = []
    width = n_in
    for _ in range(depth):
        layer = nn.Linear(width, hidden)
        nn.init.orthogonal_(layer.weight, math.sqrt(2.0))
        nn.init.zeros_(layer.bias)
        layers.extend((layer, nn.Tanh()))
        width = hidden
    head = nn.Linear(width, n_out)
    nn.init.orthogonal_(head.weight, output_gain)
    nn.init.zeros_(head.bias)
    layers.append(head)
    return nn.Sequential(*layers)


def ddqn_s18_target(
    branch_reward: torch.Tensor,
    branch_probability: torch.Tensor,
    branch_continue: torch.Tensor,
    online_next_q: torch.Tensor,
    target_next_q: torch.Tensor,
    gamma: float,
) -> torch.Tensor:
    """Double-DQN S18 target for two branches.

    Q_online selects the action while Q_target evaluates it.  Inputs have
    shapes ``[B,2]`` except Q arrays, which are ``[B,2,n_actions]``.
    """
    next_action = online_next_q.argmax(dim=-1, keepdim=True)
    next_value = target_next_q.gather(-1, next_action).squeeze(-1)
    branch_return = branch_reward + gamma * branch_continue * next_value
    return (branch_probability * branch_return).sum(dim=-1)


def sac_s18_target(
    branch_reward: torch.Tensor,
    branch_probability: torch.Tensor,
    branch_continue: torch.Tensor,
    next_logits: torch.Tensor,
    target_next_q1: torch.Tensor,
    target_next_q2: torch.Tensor,
    alpha: torch.Tensor,
    gamma: float,
) -> torch.Tensor:
    """Categorical-SAC S18 target for two branches."""
    logp = torch.log_softmax(next_logits, dim=-1)
    probability = logp.exp()
    soft_value = (
        probability * (torch.minimum(target_next_q1, target_next_q2) - alpha * logp)
    ).sum(dim=-1)
    branch_return = branch_reward + gamma * branch_continue * soft_value
    return (branch_probability * branch_return).sum(dim=-1)


class BranchReplayBuffer:
    """CPU replay of S18 branch tuples generated by a fixed qlsgym engine."""

    def __init__(self, capacity: int, n_states: int):
        self.capacity = int(capacity)
        self.state = np.empty((capacity, n_states), dtype=np.float32)
        self.action = np.empty(capacity, dtype=np.int64)
        self.next_state = np.empty((capacity, 2, n_states), dtype=np.float32)
        self.probability = np.empty((capacity, 2), dtype=np.float32)
        self.reward = np.empty((capacity, 2), dtype=np.float32)
        self.continue_mask = np.empty((capacity, 2), dtype=np.float32)
        self.size = 0
        self.position = 0

    def add(self, state, action, transition, at_horizon) -> None:
        state_np = state.detach().cpu().numpy().astype(np.float32, copy=False)
        action_np = action.detach().cpu().numpy().astype(np.int64, copy=False)
        next_np = torch.stack((transition.s0, transition.s1), dim=1).detach().cpu().numpy()
        prob_np = torch.stack((transition.pi0, transition.pi1), dim=1).detach().cpu().numpy()
        reward_np = torch.stack((transition.r0, transition.r1), dim=1).detach().cpu().numpy()
        done = torch.stack((transition.done0, transition.done1), dim=1)
        at_horizon = torch.as_tensor(at_horizon, device=done.device, dtype=torch.bool)
        cont_np = ((~done) & (~at_horizon[:, None])).detach().cpu().numpy()

        n = len(state_np)
        indices = (self.position + np.arange(n)) % self.capacity
        self.state[indices] = state_np
        self.action[indices] = action_np
        self.next_state[indices] = next_np
        self.probability[indices] = prob_np
        self.reward[indices] = reward_np
        self.continue_mask[indices] = cont_np
        self.position = int((self.position + n) % self.capacity)
        self.size = min(self.size + n, self.capacity)

    def sample(self, batch_size: int, rng: np.random.Generator,
               device: torch.device) -> dict[str, torch.Tensor]:
        indices = rng.integers(self.size, size=batch_size)
        return {
            "state": torch.as_tensor(self.state[indices], device=device),
            "action": torch.as_tensor(self.action[indices], device=device),
            "next_state": torch.as_tensor(self.next_state[indices], device=device),
            "probability": torch.as_tensor(self.probability[indices], device=device),
            "reward": torch.as_tensor(self.reward[indices], device=device),
            "continue_mask": torch.as_tensor(self.continue_mask[indices], device=device),
        }


@dataclass
class AgentStats:
    env_steps: int = 0
    gradient_steps: int = 0
    episodes: int = 0
    successes: int = 0
    wall_clock_s: float = 0.0
    episode_lengths: list[int] = field(default_factory=list)
    history: list[dict] = field(default_factory=list)

    def as_dict(self) -> dict:
        return asdict(self)


@dataclass(frozen=True)
class DDQNConfig:
    n_envs: int = 64
    total_steps: int = 200_000
    lr: float = 3e-4
    gamma: float = 1.0
    tau: float = 0.005
    batch_size: int = 256
    buffer_size: int = 100_000
    learning_starts: int = 4_096
    train_freq: int = 1
    gradient_steps: int = 1
    eps_start: float = 1.0
    eps_end: float = 0.02
    eps_fraction: float = 0.35
    hidden: int = 256
    depth: int = 2
    seed: int = 0


@dataclass(frozen=True)
class SACConfig:
    n_envs: int = 32
    total_steps: int = 200_000
    lr: float = 3e-4
    gamma: float = 0.99
    tau: float = 0.005
    batch_size: int = 256
    buffer_size: int = 100_000
    learning_starts: int = 4_096
    train_freq: int = 1
    gradient_steps: int = 1
    target_entropy_ratio: float = 0.5
    alpha: float = 0.05
    autotune_alpha: bool = True
    hidden: int = 256
    depth: int = 2
    seed: int = 0


class _OffPolicyAgent:
    def __init__(self, env, n_envs: int, buffer_size: int, seed: int):
        self.env = env.clone(n_envs)
        self.device = self.env.device
        self.n_states = self.env.n_states
        self.n_actions = self.env.n_actions
        self.buffer = BranchReplayBuffer(buffer_size, self.n_states)
        self.rng = np.random.default_rng(seed)
        self.generator = torch.Generator(device=self.device).manual_seed(seed + 1)
        self.stats = AgentStats()

    def _record_transition(self, state, action, transition) -> None:
        at_horizon = self.env.steps >= self.env.cfg.max_pulses
        self.buffer.add(state, action, transition, at_horizon)
        ended = transition.done | transition.truncated
        n_ended = int(ended.sum())
        if n_ended:
            self.stats.episode_lengths.extend(
                int(x) for x in self.env.steps[ended].detach().cpu().tolist()
            )
            self.stats.episodes += n_ended
            self.stats.successes += int(transition.done.sum())
            self.env.reset_rows(ended)

    def _log(self, name: str, values: dict) -> None:
        recent = self.stats.episode_lengths[-200:]
        record = {
            "env_steps": self.stats.env_steps,
            "gradient_steps": self.stats.gradient_steps,
            "episodes": self.stats.episodes,
            "train_mean_pulses": float(np.mean(recent)) if recent else None,
            "train_success": (
                self.stats.successes / self.stats.episodes if self.stats.episodes else None
            ),
            **values,
        }
        self.stats.history.append(record)
        mean = record["train_mean_pulses"]
        shown = float("nan") if mean is None else mean
        print(
            f"  [{name}] steps {self.stats.env_steps:>8}  "
            f"train pulses {shown:6.2f}  {values}",
            flush=True,
        )


class DDQNAgent(_OffPolicyAgent):
    """Double DQN with an exact S18 expectation over measurement outcomes."""

    def __init__(self, env, config: DDQNConfig | None = None):
        self.config = config or DDQNConfig()
        cfg = self.config
        torch.manual_seed(cfg.seed)
        super().__init__(env, cfg.n_envs, cfg.buffer_size, cfg.seed)
        self.online = build_mlp(self.n_states, self.n_actions, cfg.hidden, cfg.depth).to(self.device)
        self.target = copy.deepcopy(self.online).eval()
        self.optimizer = torch.optim.AdamW(self.online.parameters(), lr=cfg.lr, amsgrad=True)

    def epsilon(self) -> float:
        duration = max(1.0, self.config.eps_fraction * self.config.total_steps)
        fraction = min(self.stats.env_steps / duration, 1.0)
        return self.config.eps_start + fraction * (
            self.config.eps_end - self.config.eps_start
        )

    def _act(self, state: torch.Tensor) -> torch.Tensor:
        with torch.no_grad():
            greedy = self.online(transform_belief(state)).argmax(dim=-1)
        random_action = torch.randint(
            self.n_actions, (len(state),), generator=self.generator, device=self.device
        )
        explore = torch.rand(
            len(state), generator=self.generator, device=self.device
        ) < self.epsilon()
        return torch.where(explore, random_action, greedy)

    def _update(self) -> dict:
        cfg = self.config
        batch = self.buffer.sample(cfg.batch_size, self.rng, self.device)
        q = self.online(transform_belief(batch["state"]))
        q_sa = q.gather(1, batch["action"][:, None]).squeeze(1)
        with torch.no_grad():
            shape = batch["next_state"].shape
            flat = transform_belief(batch["next_state"].reshape(-1, self.n_states))
            online_next = self.online(flat).reshape(shape[0], 2, self.n_actions)
            target_next = self.target(flat).reshape(shape[0], 2, self.n_actions)
            scale = 1.0 / self.env.cfg.max_pulses
            target = ddqn_s18_target(
                batch["reward"] * scale,
                batch["probability"],
                batch["continue_mask"],
                online_next,
                target_next,
                cfg.gamma,
            )
        loss = nn.functional.smooth_l1_loss(q_sa, target)
        self.optimizer.zero_grad(set_to_none=True)
        loss.backward()
        nn.utils.clip_grad_norm_(self.online.parameters(), 10.0)
        self.optimizer.step()
        with torch.no_grad():
            for target_param, online_param in zip(self.target.parameters(), self.online.parameters()):
                target_param.mul_(1.0 - cfg.tau).add_(online_param, alpha=cfg.tau)
        return {"loss": float(loss.detach()), "epsilon": self.epsilon()}

    def train(self, log_points: int = 8) -> AgentStats:
        cfg = self.config
        state = self.env.reset(seed=cfg.seed, batch=cfg.n_envs)
        iterations = max(1, math.ceil(cfg.total_steps / cfg.n_envs))
        log_every = max(1, iterations // max(log_points, 1))
        last: dict = {}
        start = time.perf_counter()
        for iteration in range(iterations):
            before = state.clone()
            action = self._act(before)
            transition = self.env.step(action)
            self._record_transition(before, action, transition)
            state = self.env.state
            self.stats.env_steps += cfg.n_envs
            if (self.stats.env_steps >= cfg.learning_starts
                    and iteration % cfg.train_freq == 0):
                for _ in range(cfg.gradient_steps):
                    last = self._update()
                    self.stats.gradient_steps += 1
            if (iteration + 1) % log_every == 0 or iteration + 1 == iterations:
                self._log("ddqn", last)
        self.stats.wall_clock_s = time.perf_counter() - start
        return self.stats


class DiscreteSACNetwork(nn.Module):
    def __init__(self, n_states: int, n_actions: int, hidden: int, depth: int,
                 alpha: float):
        super().__init__()
        self.actor = build_mlp(n_states, n_actions, hidden, depth, output_gain=0.01)
        self.q1 = build_mlp(n_states, n_actions, hidden, depth)
        self.q2 = build_mlp(n_states, n_actions, hidden, depth)
        self.log_alpha = nn.Parameter(torch.tensor(math.log(alpha), dtype=torch.float32))


class DiscreteSACAgent(_OffPolicyAgent):
    """Categorical SAC with twin critics and an exact S18 branch target."""

    def __init__(self, env, config: SACConfig | None = None):
        self.config = config or SACConfig()
        cfg = self.config
        if cfg.gamma >= 1.0:
            raise ValueError("entropy-regularised SAC requires gamma < 1 for this continuing soft target")
        torch.manual_seed(cfg.seed)
        super().__init__(env, cfg.n_envs, cfg.buffer_size, cfg.seed)
        self.network = DiscreteSACNetwork(
            self.n_states, self.n_actions, cfg.hidden, cfg.depth, cfg.alpha
        ).to(self.device)
        self.target_q1 = copy.deepcopy(self.network.q1).eval()
        self.target_q2 = copy.deepcopy(self.network.q2).eval()
        self.actor_optimizer = torch.optim.Adam(self.network.actor.parameters(), lr=cfg.lr)
        critic_params = list(self.network.q1.parameters()) + list(self.network.q2.parameters())
        self.critic_optimizer = torch.optim.Adam(critic_params, lr=cfg.lr)
        self.alpha_optimizer = torch.optim.Adam([self.network.log_alpha], lr=cfg.lr)
        self.target_entropy = cfg.target_entropy_ratio * math.log(self.n_actions)

    def _act(self, state: torch.Tensor) -> torch.Tensor:
        with torch.no_grad():
            probability = torch.softmax(self.network.actor(transform_belief(state)), dim=-1)
            return torch.multinomial(probability, 1, generator=self.generator).squeeze(-1)

    def _update(self) -> dict:
        cfg = self.config
        batch = self.buffer.sample(cfg.batch_size, self.rng, self.device)
        state = transform_belief(batch["state"])
        action = batch["action"]
        with torch.no_grad():
            shape = batch["next_state"].shape
            next_state = transform_belief(
                batch["next_state"].reshape(-1, self.n_states)
            )
            next_logits = self.network.actor(next_state).reshape(
                shape[0], 2, self.n_actions
            )
            next_q1 = self.target_q1(next_state).reshape(shape[0], 2, self.n_actions)
            next_q2 = self.target_q2(next_state).reshape(shape[0], 2, self.n_actions)
            scale = 1.0 / self.env.cfg.max_pulses
            target = sac_s18_target(
                batch["reward"] * scale,
                batch["probability"],
                batch["continue_mask"],
                next_logits,
                next_q1,
                next_q2,
                self.network.log_alpha.exp(),
                cfg.gamma,
            )

        q1 = self.network.q1(state).gather(1, action[:, None]).squeeze(1)
        q2 = self.network.q2(state).gather(1, action[:, None]).squeeze(1)
        critic_loss = nn.functional.mse_loss(q1, target) + nn.functional.mse_loss(q2, target)
        self.critic_optimizer.zero_grad(set_to_none=True)
        critic_loss.backward()
        self.critic_optimizer.step()

        logits = self.network.actor(state)
        logp = torch.log_softmax(logits, dim=-1)
        probability = logp.exp()
        with torch.no_grad():
            q_min = torch.minimum(self.network.q1(state), self.network.q2(state))
        alpha = self.network.log_alpha.exp().detach()
        actor_loss = (probability * (alpha * logp - q_min)).sum(dim=-1).mean()
        self.actor_optimizer.zero_grad(set_to_none=True)
        actor_loss.backward()
        self.actor_optimizer.step()

        entropy = -(probability.detach() * logp.detach()).sum(dim=-1).mean()
        if cfg.autotune_alpha:
            alpha_loss = self.network.log_alpha.exp() * (
                entropy.detach() - self.target_entropy
            )
            self.alpha_optimizer.zero_grad(set_to_none=True)
            alpha_loss.backward()
            self.alpha_optimizer.step()

        with torch.no_grad():
            for target_net, source_net in (
                (self.target_q1, self.network.q1),
                (self.target_q2, self.network.q2),
            ):
                for target_param, source_param in zip(target_net.parameters(), source_net.parameters()):
                    target_param.mul_(1.0 - cfg.tau).add_(source_param, alpha=cfg.tau)
        return {
            "critic_loss": float(critic_loss.detach()),
            "actor_loss": float(actor_loss.detach()),
            "entropy": float(entropy),
            "alpha": float(self.network.log_alpha.detach().exp()),
        }

    def train(self, log_points: int = 8) -> AgentStats:
        cfg = self.config
        state = self.env.reset(seed=cfg.seed, batch=cfg.n_envs)
        iterations = max(1, math.ceil(cfg.total_steps / cfg.n_envs))
        log_every = max(1, iterations // max(log_points, 1))
        last: dict = {}
        start = time.perf_counter()
        for iteration in range(iterations):
            before = state.clone()
            action = self._act(before)
            transition = self.env.step(action)
            self._record_transition(before, action, transition)
            state = self.env.state
            self.stats.env_steps += cfg.n_envs
            if (self.stats.env_steps >= cfg.learning_starts
                    and iteration % cfg.train_freq == 0):
                for _ in range(cfg.gradient_steps):
                    last = self._update()
                    self.stats.gradient_steps += 1
            if (iteration + 1) % log_every == 0 or iteration + 1 == iterations:
                self._log("sac_discrete", last)
        self.stats.wall_clock_s = time.perf_counter() - start
        return self.stats


class TorchPolicy:
    """qlsgym Policy adapter for DDQN or categorical-SAC networks."""

    stateful = False

    def __init__(self, network: nn.Module, device: torch.device | str,
                 stochastic: bool, seed: int = 0):
        self.network = network.eval()
        self.device = torch.device(device)
        self.stochastic = bool(stochastic)
        self.seed = int(seed)

    def act_batch(self, beliefs, t, rng):
        del t
        belief = torch.as_tensor(np.asarray(beliefs), device=self.device)
        with torch.no_grad():
            logits = self.network(transform_belief(belief)).detach().cpu().numpy()
        if not self.stochastic:
            return logits.argmax(axis=-1).astype(np.int64)
        logits -= logits.max(axis=-1, keepdims=True)
        probability = np.exp(logits)
        probability /= probability.sum(axis=-1, keepdims=True)
        uniforms = rng.random(len(probability))
        action = (probability.cumsum(axis=-1) < uniforms[:, None]).sum(axis=-1)
        return np.minimum(action, probability.shape[-1] - 1).astype(np.int64)

    def act(self, belief, t, rng):
        return int(self.act_batch(np.asarray(belief)[None], t, rng)[0])


def ddqn_policy(agent: DDQNAgent) -> TorchPolicy:
    return TorchPolicy(agent.online, agent.device, stochastic=False, seed=agent.config.seed)


def sac_policy(agent: DiscreteSACAgent, stochastic: bool = True) -> TorchPolicy:
    return TorchPolicy(
        agent.network.actor, agent.device, stochastic=stochastic, seed=agent.config.seed
    )
